:construction_worker: add commit for doc changes

diff --git a/.github/workflows/hello-world.yml b/.github/workflows/hello-world.yml
--- a/.github/workflows/hello-world.yml
+++ b/.github/workflows/hello-world.yml
@@ -72,6 +72,21 @@ jobs:
           path: gh-pages
           ref: gh-pages
 
+      - name: Commit documentation changes
+        run: |
+          rm -r gh-pages/*
+          cp -r main/docs/build/html/* gh-pages/
+          cd  gh-pages/
+          touch .nojekyll
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git status
+          git add .
+          git status
+          # The command below will fail if no changes were present, so we ignore that.
+          git commit -m "doc from ${{ github.ref }} @ ${{ github.sha }}" || true
+          git status
+
       - name: Deploy GraphAI API
         run: |
           # graphai/api/deploy.sh -p ${{ vars.api_test_port }}
